services:
  flink-jobmanager:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    networks:
      - flink-network

  flink-taskmanager-1:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink-taskmanager-1
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    networks:
      - flink-network

  flink-taskmanager-2:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink-taskmanager-2
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    networks:
      - flink-network

  flink-taskmanager-3:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink-taskmanager-3
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge